apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: weatherforecast
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: steeltoe-weatherforecast
  name: weatherforecast
  namespace: default
spec:
  params:
  - name: debug
    value: "true"
  - name: live-update
    value: "true"
  source:
    image: gcr.io/pa-mbrodi/temp/weatherforecast@sha256:091eefeec21157732b6639e91d4215796eeead4f48f5018a33d88f64be303861
